import './globals.css'
import { Montserrat } from 'next/font/google'
import Nav from '@components/Nav'
import Footer from '@components/Footer'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'AK SIMBIOSIS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <img src="/assets/bg-rect.svg" alt="" className='w-full fixed z-[-1]'/>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
